PREFIX sro: <https://data.vlaanderen.be/ns/slimmeraadpleegomgeving#>
PREFIX locn: <http://www.w3.org/ns/locn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>

INSERT DATA {
  GRAPH <http://mu.semte.ch/graphs/public> {
  <https://data.aalter.be/id/agendapunten/25.0211.0053.0388>
    rdf:type <http://data.vlaanderen.be/ns/besluit#Agendapunt> ;
    sro:heeftLocatie <http://data.lblod.info/id/adressen/1234> .

  <http://data.lblod.info/id/adressen/1234>
    rdf:type locn:Address ;
    locn:geometry <http://data.lblod.info/id/geometries/5678> .

  <http://data.lblod.info/id/geometries/5678>
    rdf:type locn:Geometry ;
    geosparql:asWKT "<http://www.opengis.net/def/crs/EPSG/0/31370> POINT(159755.86609040055 168546.2321244767)"^^<http://www.opengis.net/ont/geosparql#wktLiteral> .
  }
}
